config/routes.rb
Letitfreeme::Application.routes.draw do

  resources :transactions
  resources :categories do
    resources :postings
  end
  resources :messages
  resources :postings
  resources :users

  match '/auth/twitter/callback', :to => 'sessions#create_with_twitter'
  match '/auth/:provider/callback', :to => 'sessions#create'
  
  match '/sessions/logout', :to => 'sessions#logout'
  resources :postings, :only=>[:index]
  resources :sessions, :only=>[:create,:logout]
  
  root :to=>'pages#index'
  

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :sender, :class_name=>'User', :foreign_key => "sender_id"
  belongs_to :recipient, :class_name=>'User', :foreign_key => "recipient_id"
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_filter :mustbeloggedintoview
  
  def mustbeloggedintoview
    unless (signed_in?)
      flash[:error] = "You must be logged in"
      redirect_to new_user_path
    end
  end
  
  def new
    @message = Message.new
     
    @posting = Posting.find_by_id(params[:posting])
    @post_author = User.find_by_id(@posting.user_id)
    @recipient = User.find_by_id( params[:recipient_id])
    
    @message.subject = @posting.title
    @message.recipient_id = @recipient.id
    @message.sender_id = current_user.id
    
    respond_to do |format|
       format.html # new.html.erb
    end
  end
  
  def index
    logger.info("messages index action")
    @title = 'Message Centre'
    
    #if(signed_in?)
      @users = User.includes(:sent_messages, :received_messages).where('messages.sender_id = ? OR messages.recipient_id = ?', @current_user.id, @current_user.id)
      @users.all.delete(@current_user)
      
      @sentmessages = @current_user.sent_messages
      @receivedmessages = @current_user.received_messages
      
      @messages = (@sentmessages | @receivedmessages) << Message.new(:subject=>'Welcome!', :body=>'Welcome to letitfree.me!', :created_at=>@current_user.created_at)
      # @messages.sort_by { |o|
      #   o.created_at
      # }
      
      respond_to do |format|
        format.html # new.html.erb
      end
    #else
    #  return redirect_to root_path
    #end
  end
  
  def show
    @message = Message.find_by_id(params[:id])
    
    if(@message.recipient_id == current_user.id)
      @message.read_at = Time.now() 
      @message.save
    end
  end
  
  def create
    @message = Message.new(params[:message])
    @message.sender = @current_user
    #@message.recipient = Message.find_by_login(params[:message][:to])

    if @message.save
      flash[:notice] = "Message sent"
      redirect_to messages_path
    else
      render :action => :new
    end
  end
  
  def delete_selected
    if request.post?
      if params[:delete]
        params[:delete].each { |id|
          @message = Message.find(:first, :conditions => ["messages.id = ? AND (sender_id = ? OR recipient_id = ?)", id, @message, @message])
          @message.mark_deleted(@message) unless @message.nil?
        }
        flash[:notice] = "Messages deleted"
      end
      redirect_to user_message_path(@message, @messages)
    end
  end
end

app/views/messages/_inbox.html.erb
<h2>Inbox</h2>
<table>
	<tr>
		<th>Del?</th>
		<th>Sent</th>
		<th>Sender</th>
		<th>Sent</th>
	</tr>
	<% if @messages.size == 0 %>
		<tr>
			<td colspan="4">
				No messages
			</td>
		</tr>
	<% else %>
		<% for message in @messages %>
			<tr>
				<td><%= check_box_tag "delete[]", message.id %></td>
				<td>
					<% if message.read? %>
					  <%= link_to h(message.subject), user_message_path(@message, message) %>
					<% else %>
					  <%= link_to "#{h(message.subject)} (unread)", user_message_path(@message, message) %>
					<% end %>
				</td>
				<td><%= link_to h(message.sender.login), user_path(@message) %></td>
		    <td><%=h message.created_at.to_s(:long) %></td>
			</tr>
		<% end %>
		<tr>
			<td colspan="4">
				<%= submit_tag "Delete" %>
			</td>
		</tr>
	<% end %>
</table>
<%= link_to "Sent", user_messages_path(@message, :mailbox => :sent)%> |
<%= link_to "Compose", new_user_message_path(@message)%>

app/views/messages/_list_messages.html.erb
<% messages.each do |message| %>
  <tr>
    <td>
      <% if (message.read_at.nil? && renderUnreadFlag)%>  
        <strong>Unread</strong> &nbsp;
      <% else %>
        Read &nbsp;
      <% end %>
    </td>
    <td>
      <%= link_to(message.subject,message)%>
    </td>
  </tr>
<% end %>

app/views/messages/_message.html.erb
<div class='message' data-message-id='<%= message.id %>' data-message-user-id='<%= (message.sender == @current_user ? message.recipient.id : message.sender.id) rescue 0 %>'>
  <h1>
    <%= message.subject %>
  </h1>
  <%= link_to image_tag(message.sender.gravatar_url(:size=>40), :class=>'gravatar'), message.sender if message.sender %>
  <div class='details'>
    <span class='time'><%= time_ago_in_words message.created_at %> ago</span>
  </div>
  <div class='body'>
    <%= message.body %>
  </div>
</div>

app/views/messages/_sent.html.erb
<h2>Sent</h2>
<table>
	<tr>
		<th>Del?</th>
		<th>Subject</th>
		<th>To</th>
		<th>Sent</th>
	</tr>
	<% if @messages.size == 0 %>
		<tr>
			<td colspan="4">
				No messages
			</td>
		</tr>
	<% else %>
		<% for message in @messages %>
			<tr>
				<td><%= check_box_tag "delete[]", message.id %></td>
				<td><%= link_to h(message.subject), user_message_path(@message, message) %></td>
  			<td><%= link_to h(message.recipient.login), user_path(@message) %></td>
			  <td><%=h message.created_at.to_s(:long) %></td>
			</tr>
		<% end %>
		<tr>
			<td colspan="4">
				<%= submit_tag "Delete" %>
			</td>
		</tr>
 	<% end %>
</table>
<%= link_to "Inbox", user_messages_path(@message)%>

app/views/messages/index.html.erb
<%= content_for :head do %>
  <%= stylesheet_link_tag 'messages' %>
<% end %>
<%= content_for :headerMenu do %>
  <%= @messages.size %> messages
<% end %>

<section id='messages'>
  <div id='messageUserThreads'>
    <div id='coversationsHeader'>
      <h1>Conversations</h1>
    </div>
    <% @first_user = true %>
    <% for user in @users %>
    <div class='user' data-user-id='<%= user.id %>' data-user-name='<%= user.name || "Username" %>'>
      <div class='content'>
        <%= image_tag(user.gravatar_url(:size=>32), :class=>'gravatar') %>
        <div class='userName'>
          <strong><%= user.name || 'Username' %></strong>
          <span class='fullName'><%= user.first_name ? (user.first_name + ' ' + user.last_name) : 'Full Name' %></span>
        </div>
        <div class='details'>
          <% last_message = @messages.find {|message| (message.recipient == user || message.sender == user) ? message.created_at : false } %>
          <date class='lastMessageDate'><%= time_ago_in_words last_message.created_at %> ago</date>
          <% sum = 0 %>
          <% @messages.each{|message| sum += ((message.recipient == user || message.sender == user) ? 1 : 0)  } %>
          <div class='messageCount'><%= sum %></div>
        </div>
      </div>
    </div>
    <% @first_user = false; end %>
    <div class='user' data-user-id='0'>
      <div class='content'>
        <div class='userName'>
          <strong>Letitfree.me Team</strong>
          <span class='fullName'></span>
        </div>
        <div class='details'>
          <% last_message = @messages.find {|message| (message.recipient == user || message.sender == user) ? message.created_at : false } %>
          <date class='lastMessageDate'><%= time_ago_in_words last_message.created_at %> ago</date>
          <div class='messageCount'>1</div>
        </div>
      </div>
    </div>
  </div>
  
  <div id='messageReader'>
    <div id='newMessage'>
      <%= form_for Message.new do |f| %>
        <h1>Reply to <span class='username'>Username</span>:</h1>
        <button type='submit'>Send</button>
        <%= f.text_field :subject %>
        <%= f.text_area :body %>
        <%= f.hidden_field :recipient_id, %>
      <% end %>
    </div>
    <div id='messageList' class='messageList'>
      <%= render @messages %>
    </div>
  </div>
  <div style='clear: left'></div>
</section>

<%= h(flash[:error])%>

<script>
  $(document).ready(function(){
     var selected = $('#messageUserThreads .user').eq(0),
         changeMailView = function(e){
           var selected = $(e),
               selectedID = selected.attr('data-user-id'),
               current_user_label = $('#newMessage .username');
           $('#messageUserThreads .selected').removeClass('selected');
           selected.addClass('selected');
           $('#messageList .message').hide();
           $('#messageList .message[data-message-user-id="'+selectedID+'"]').show();
           current_user_label.html(selected.attr('data-user-name'));
           
           $('#message_recipient_id').val(selectedID);
         }
     
     $('#messageUserThreads .user').click(function(e){
       changeMailView(this);
     });
     
     selected.click();
   });
</script>

app/views/messages/new.html.erb
<% form_for @message do |f| %>

  <%= f.hidden_field :recipient_id, :values=> @message.recipient_id %>
  <%= f.hidden_field :sender_id, :values=> @message.sender_id %>

  <p>
    <%= f.label :recipient %>
    <%= f.label @recipient.name %>
  </p>

  <p>
    <%= f.label :subject %>
    <%= f.text_field :subject%>
  </p>

  <p>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= submit_tag "Send" %>
  </p>
<% end %>

app/views/messages/show.html.erb
<p><strong>From:</strong> <%= @message.sender_id == current_user.id ? link_to("You", user_path(current_user)) : link_to(h(@message.sender_id), user_path(current_user)) %></p>
<p><strong>Received:</strong> <%= @message.created_at.to_s(:long) %></p>
<p><strong>To:</strong> <%= @message.recipient_id == current_user.id ? link_to("You", user_path(current_user)) : link_to(h(@message.recipient_id), user_path(current_user)) %></p>

<p>
  <strong>Subject</strong>
  <%=h @message.subject %>
</p>
<p>

<p>
  <strong>Message</strong><br />
  <%=h @message.body %>
</p>
<p>
  <% if @message.recipient_id == current_user.id %>
	  <%= link_to "Reply", new_message_path(@user, :reply_to => @message) %> |
  <% end %>
  <%= link_to "Inbox", messages_path%>
</p>