config/routes.rb
Letitfreeme::Application.routes.draw do

  resources :transactions
  resources :categories do
    resources :postings
  end
  resources :messages
  resources :postings
  resources :users

  match '/auth/twitter/callback', :to => 'sessions#create_with_twitter'
  match '/auth/:provider/callback', :to => 'sessions#create'
  
  match '/sessions/logout', :to => 'sessions#logout'
  resources :postings, :only=>[:index]
  resources :sessions, :only=>[:create,:logout]
  
  root :to=>'pages#index'
  

end

app/models/user.rb
class User < ActiveRecord::Base
  #validates_presence_of :email
  
  
  has_many :authorizations
  has_many :postings
  belongs_to :location

  include Gravtastic
  gravtastic
  
  has_many :sent_messages, :class_name=>'Message', :foreign_key => "sender_id"
  has_many :received_messages, :class_name=>'Message', :foreign_key => "recipient_id"

  cattr_reader :per_page
  @@per_page = 32
  
  def self.create_from_hash!(hash)
    create(:name => hash['user_info']['name'])
  end
  
  def read_message_count
    eval 'Message.count(:conditions => ["recipient_id = ? AND read_at IS NOT NULL", self])'
  end
  
  def unread_message_count
    eval 'Message.count(:conditions => ["recipient_id = ? AND read_at IS NULL", self])'
  end

  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :filterEditPermissions, :only => [:edit,:update]
  
  def filterEditPermissions
    unless(canUserEditCurrentUser?)
      redirect_to users_path
    end
  end
  
  def canUserEditCurrentUser?
    if(current_user.present?)
      if(current_user.is_moderator)
        return true
      else
        return current_user.id == params[:id].to_i
      end
    end
    return false
  end
  
  def new

  end
  
  def create
    redirect_to :controller => "sessions",:action=>"create"
  end

  # GET /users
  # GET /users.xml
  def index
    @title = 'User Directory'
    @users = User.where('email not ?', nil).order('first_name DESC').paginate(:page => params[:page], :per_page => User.per_page)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @users }
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user ||= User.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # PUT /Users/1
  # PUT /Users/1.xml
  def update
    
    @user = User.find(params[:id])
    
    bSave = true
    
    if(bSave)
      bSave = @user.update_attribute(:bio,params[:user][:bio])
    end
    
    if(bSave)
      bSave = @user.update_attribute(:location,params[:user][:location])
    end
    
    if(bSave)
      bSave = @user.update_attribute(:first_name,params[:user][:first_name])
    end
    
    if(bSave)
      bSave = @user.update_attribute(:last_name,params[:user][:last_name])
    end
    if(bSave)
      bSave = @user.update_attribute(:name,params[:user][:name])
    end
    
    if(bSave)
      bSave = @user.update_attribute(:email,params[:user][:email])
      #@user.email = params[:user][:email]
      #bSave = @user.save
    end
    
    #debugger
    respond_to do |format|
      if bSave
        format.html { redirect_to(@user) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # GET /users/1/edit
  def edit
   @user = User.find(params[:id])   
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_path) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<% form_for(@user) do |f| %>
  
<table>
  <tr>
    <td>User Name&nbsp;</td>
    <td><%= f.text_field :name %></td>
  </tr>
  <tr>
    <td>First Name&nbsp;</td>
    <td><%= f.text_field :first_name %></td>
  </tr>
  <tr>
    <td>Last Name&nbsp;</td>
    <td><%= f.text_field :last_name %></td>
  </tr>
  <tr>
    <td>Email&nbsp;</td>
    <td><%= f.text_field :email %></td>
  </tr>
  <tr>
    <td>Location &nbsp;</td>
    <td><%= f.text_field :location,:disabled => :true %></td>
  </tr>
  <tr>
    <td>Bio&nbsp;</td>
    <td><%= f.text_area :bio,:size=>"22x10" %></td>
  </tr>

</table>
  <%= f.submit "Update user" %><%= link_to "Cancel",user_path(@user) %>
<% end %>

app/views/users/index.html.erb
<%= content_for :headerMenu do %>
  <%= link_to "Sign in",new_user_path,:class=>'button' %>
<% end %>

<% for user in @users %>
  <div class='user' data-user-id='<%= user.id %>'>
    <div class='content'>
      <%= image_tag(user.gravatar_url(:size=>32), :class=>'gravatar') %>
      <div class='userName'>
        <strong><%= h user.name %> </strong>
        <span class='fullName'><%= user.first_name ? (user.first_name + ' ' + user.last_name) : 'Full Name' %></span>
      </div>
    </div>
  </div>
<% end %>

<div style='clear: left'></div>
<%= will_paginate @users %> 

<style>
.user {
  float: left;
  width: 220px;
  height: 80px;
}
.user .gravatar {
  float: left;
}
.user .content {
  padding: 5px;
}
.user .userName {
  margin-left: 40px;
}
.user .userName strong {
  display: block;
}
div.pagination {
  width: 300px;
  margin: 20px auto;
}
</style>

app/views/users/new.html.erb
<%= render 'shared/login_options' %>

app/views/users/show.html.erb
<table>
  <tr>
    <td>User Name&nbsp;</td>
    <td><%= @user.name %></td>
  </tr>
  <% if @user == @current_user %>
  <tr>
    <td>First Name&nbsp;</td>
    <td><%= @user.first_name %></td>
  </tr>
  <tr>
    <td>Last Name&nbsp;</td>
    <td><%= @user.last_name %></td>
  </tr>
  <tr>
    <td>Location &nbsp;</td>
    <td><%= @user.location %></td>
  </tr>
  <tr>
    <td>Bio&nbsp;</td>
    <td><%= @user.bio %></td>
  </tr>
  <tr>
    <td>Email&nbsp;</td>
    <td><%= @user.email %></td>
  </tr>
  <% end if signed_in? %>
</table>

<% if @user == @current_user %>

<table>
  <tr>
    <td>Number of unread messages&nbsp;</td>
    <td><%= link_to @user.unread_message_count,messages_path %></td>
  </tr>
  <tr>
    <td>Number of read messages&nbsp;</td>
    <td><%= link_to @user.read_message_count,messages_path %></td>
  </tr>
  
</table>



<%= link_to "Edit User",edit_user_path(@user)%>

<% end if signed_in? %>