config/routes.rb
Letitfreeme::Application.routes.draw do

  resources :transactions
  resources :categories do
    resources :postings
  end
  resources :messages
  resources :postings
  resources :users

  match '/auth/twitter/callback', :to => 'sessions#create_with_twitter'
  match '/auth/:provider/callback', :to => 'sessions#create'
  
  match '/sessions/logout', :to => 'sessions#logout'
  resources :postings, :only=>[:index]
  resources :sessions, :only=>[:create,:logout]
  
  root :to=>'pages#index'
  

end

app/models/posting.rb
class Posting < ActiveRecord::Base
  scope :recent, order('created_at DESC').limit(5)
  
  belongs_to :category
  belongs_to :user
  belongs_to :location
  
  #validates_presence_of :location

  cattr_reader :per_page
  @@per_page = 16
end

app/controllers/postings_controller.rb
class PostingsController < ApplicationController
  before_filter :get_filters
  before_filter :create_new, :only => [:new,:create]
  before_filter :create_edit, :only => [:update,:edit]
  before_filter :can_delete, :only => [:destroy]

  # GET /postings
  # GET /postings.xml
  def index
    if(@category)
      @title = 'Item Postings by Category'
      @listTitle = @category.name.titleize
      @postings = @category.postings.paginate(:page => params[:page])
    else
      @title = 'Item Postings'
      @listTitle = 'Recent Items in Edmonton'
      @postings = Posting.paginate(:page => params[:page])
    end
    
    # categories = File.open(File.join(Rails.root, 'public', 'data', 'categories.json'), 'r').read();
    # @categories = ActiveSupport::JSON.decode(categories)
    
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.ms_html { render :partial=>'posting.html.erb', :locals=>{:posting=>false} }
      format.xml  { render :xml => @postings }
    end
  end

  # GET /postings/1
  # GET /postings/1.xml
  def show
    @posting = Posting.find(params[:id])
    @author = User.find_by_id(@posting.user_id)

    respond_to do |format|
      format.html # show.html.erb
      format.ms_html { render :partial=>'posting.html.erb', :locals=>{:posting=>@posting} }
      format.xml  { render :xml => @posting }
    end
  end

  # GET /postings/new
  # GET /postings/new.xml
  def new
    @posting = Posting.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @posting }
    end
  end

  # GET /postings/1/edit
  def edit
    @posting = Posting.find(params[:id])
  end

  # POST /postings
  # POST /postings.xml
  def create
    @posting = Posting.new(params[:posting])
    @posting.user_id = current_user.id

    respond_to do |format|
      if @posting.save
        format.html { redirect_to(@posting, :notice => 'Posting was successfully created.') }
        format.xml  { render :xml => @posting, :status => :created, :location => @posting }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @posting.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /postings/1
  # PUT /postings/1.xml
  def update
    @posting = Posting.find(params[:id])

    respond_to do |format|
      if @posting.update_attributes(params[:posting])
        format.html { redirect_to(@posting, :notice => 'Posting was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @posting.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /postings/1
  # DELETE /postings/1.xml
  def destroy
    @posting = Posting.find(params[:id])
    @posting.destroy

    respond_to do |format|
      format.html { redirect_to(postings_url) }
      format.xml  { head :ok }
    end
  end
  
  private
  def get_filters
    puts(params.inspect)
    if(category = params[:category_id])
      @category = Category.find(category)
    end
  end
  
  def create_new
    unless(signed_in?)
      flash[:error] = "You must be signed in to create a posting."
      redirect_to new_user_path
    end
  end
  
  def create_edit
    unless(signed_in?)
      flash[:error] = "You must be signed in to edit a posting."
      redirect_to postings_path(params[:id])
    end
  end
  
  def can_delete
    unless(current_user_admin?)
      redirect_to postings_path(params[:id])
    end
  end
end

app/helpers/postings_helper.rb
module PostingsHelper  
  def title(posting)
    posting.title
  end
  def link(posting)
    url_for posting
  end
  def location(posting)
    posting.location
  end
  def description(posting)
    truncate(posting.description, :length => 250)
  end
  def category(posting)
    if(posting.present? && posting.category.present? && posting.category.name.present?)
      link_to(posting.category.name, posting.category)
    end
  end
  def age(posting)
    time_ago_in_words posting.created_at
  end
end

app/views/postings/_form.html.erb
<%= form_for(@posting) do |f| %>
  <% if @posting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@posting.errors.count, "error") %> prohibited this posting from being saved:</h2>

      <ul>
      <% @posting.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :date_expires %><br />
    <%= f.time_select :date_expires %>
  </div>
  <div class="field">
    <%= f.label :date_closed %><br />
    <%= f.time_select :date_closed %>
  </div>
  <div class="field">
    <%= f.label :new %><br />
    <%= f.check_box :new %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/postings/_posting.html.erb
<div class='posting'>
  <img />
  <h2><%= link_to ms(posting, :title), ms(posting, :link) %></h2>
  <h3>
    <span class='category'><%= ms posting, :category %></span>
    <span class='location'>Near <%= ms posting, :location %></span>
    <time class='age'><%= ms posting, :age %></time>
  </h3>
  <p><%= ms posting, :description %></p>
  <div style='clear: left'></div>
</div>

app/views/postings/edit.html.erb
<h1>Editing posting</h1>

<%= render 'form' %>

<%= link_to 'Show', @posting %> |
<%= link_to 'Back', postings_path %>

app/views/postings/index.html.erb
<%= content_for :head do %>
  <%= stylesheet_link_tag 'postings' %>
<% end %>
<%= content_for :headerMenu do %>
  <%= link_to '<span>+</span>Offer an Item'.html_safe(), new_posting_path, :class=>'offerItem button hasIcon' %>
<% end %>

<nav id='categories'>
  <h1>Categories</h1>
  <ul>
    <li class='current'><%= link_to_unless_current 'All', postings_path %></li>
  <% for category in @categories.sort_by(&:name) %>
    <li class='<%= 'top' %>'><%= link_to_unless_current category['name'], [category, 'postings'] %> <!--(<%#=category.postings.count if category.postings.count > 0 %>)--></li>
  <% end%>
  </ul>
  <button data-action='showAllCategories'>More</button>
</nav>

<section id='postingsList'>
  <header>
    <h1><%= @listTitle %></h1>
    <div>
      <!--Find by tag: <a>Lorem</a>, <a>ipsum dolor</a>, <a>sit amet</a>, <a>consectetur</a>, <a> adipiscing</a>, <a>elit</a>-->
    </div>
  </header>
  <%= flash[:error] %>
  <%= will_paginate @postings %> 
  <%= render @postings %>
  <%= will_paginate @postings %> 
</section>

<div style='clear:left'></div>
<script>
$('#categories [data-action="showAllCategories"]').bind('click', function(e){
  $('#categories li').show();
  $(this).hide();
});
</script>

app/views/postings/new.html.erb
<h1>New posting</h1>

<%= render 'form' %>

<%= link_to 'Back', postings_path %>

app/views/postings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @posting.title %>
</p>

<p>
  <b>Description:</b>
  <%= @posting.description %>
</p>

<p>
  <b>Date expires:</b>
  <%= @posting.date_expires %>
</p>

<p>
  <b>Date closed:</b>
  <%= @posting.date_closed %>
</p>

<p>
  <b>Location:</b>
  <%= @posting.location %>
</p>

<p>
  <b>New:</b>
  <%= @posting.new %>
</p>

<p>
  <b>Poster:</b>
  <%= image_tag(@author.gravatar_url(:size=>32), :class=>'gravatar') %>
  <%= link_to(@author.name,@author)%> &nbsp; 
</p>

<p>
  <% if((signed_in?) && (@author.id == current_user.id)) %>
    Ask a question about this item (this is your own item)
  <% else %>
    <%= link_to("Ask a question about this item",new_message_path(:posting => @posting,:recipient_id => @author ))%>
  <% end %>
  <% if((signed_in?) && (@author.id == current_user.id)) %>
    Request this item (this is your own item)
  <% else %>
    <%= link_to("Request this item",new_transaction_path(:posting => @posting))%>
  <% end %>
</p>


<%= link_to 'Edit', edit_posting_path(@posting) %> |
<%= link_to 'Back', postings_path %>