config/routes.rb
Letitfreeme::Application.routes.draw do

  resources :transactions
  resources :categories do
    resources :postings
  end
  resources :messages
  resources :postings
  resources :users

  match '/auth/twitter/callback', :to => 'sessions#create_with_twitter'
  match '/auth/:provider/callback', :to => 'sessions#create'
  
  match '/sessions/logout', :to => 'sessions#logout'
  resources :postings, :only=>[:index]
  resources :sessions, :only=>[:create,:logout]
  
  root :to=>'pages#index'
  

end

app/views/layouts/_home.html.erb
<section id='content' class='home'>
  <%= yield %>
</section>

app/views/layouts/_interior.html.erb
<section id='content' class='interior'>
  <header id='contentHeader'>
    <h1><%= @title %></h1>
    <nav class='sectionMenu'>
      <%= yield :headerMenu %>
    </nav>
  </header>

  <div id='bodyHolder'>
    <%= yield %>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>Letitfree.me - <%= @title %></title>
  <%= csrf_meta_tag %>
  <%= stylesheet_link_tag 'reset', 'app' %>
  <link href='http://fonts.googleapis.com/css?family=Neuton&subset=latin' rel='stylesheet' type='text/css'>
  <script src="http://www.google.com/jsapi"></script>
  <script>
    google.load("jquery", "1.4.2");
  </script>
  <%= yield :head %>
</head>
<body>
  <div id='wrapper'>
    <header>
      <div class='container'>
      <h1><a href='/'>let<span class='mid'>it</span>free<span class='end'>.me</span></a></h1>
      <h2>
        <span>Find or Offer Items for Free in</span>
        Edmonton
      </h2>
      <nav>
        <ul>
          <li><%= active_link_to 'Home', root_path %></li>
          <li><%= active_link_to 'Postings', postings_path %></li>
          <% if (signed_in?) %>
            <li><%= active_link_to 'Messages', messages_path %></li>
          <% end %>
          <li><%= active_link_to 'Users', users_path %></li>
        </ul>
      </nav>
      </div>
    </header>
    
    <%= render :partial=>'layouts/'+@bodylayout %>
    
    <footer>
      <nav>
        <ul>
          <li>
            <%= link_to 'Home', '/' %>
            <% if(signed_in?) %>
              <%= link_to 'Sign Out', sessions_logout_path %>
            <% else %>
              <%= link_to 'Sign In', new_user_path %>
            <% end %>
          </li>
        </il>
      </nav>
      <%= link_to image_tag(@current_user.gravatar_url(:size=>32), :class=>'gravatar'), @current_user if signed_in? %>
    </footer>
  </div>
</body>
<%= javascript_include_tag 'rails', 'application' %>
</html>